"""table creation

Revision ID: 4427fed096dc
Revises: 143f2af75155
Create Date: 2023-04-17 21:08:31.207810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4427fed096dc'
down_revision = '143f2af75155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nearest_star', sa.String(), nullable=True))
        batch_op.drop_column('neartest_star')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('neartest_star', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('nearest_star')

    # ### end Alembic commands ###
